[Service]
Environment=MESSEAUTO_DATABASE_PI_URL=http://10.42.0.12:9000
Environment=MESSEAUTO_DATABASE_TIMEOUT=1.0
Environment=MESSEAUTO_ESP32_ACTOR_ENABLED=0
Environment=MESSEAUTO_PULSE_DURATION=0.12
